### ISSUE TITLE
make-base-vm need sudo to run docker

### ISSUE THREAD

**Issue by AbcSxyZ** [micaelmalta/gitian-builder-dogecoin#2]
While running setup script, I'm getting this following docker error : 
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=base-trusty-amd64.Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&pull=1&rm=1&shmsize=0&t=base-trusty-amd64&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
```

Idk how you're running your script, but the [following line](https://github.com/micaelmalta/gitian-builder-dogecoin/blob/153b961cd312674402b9d9e8658c2f1c169fb054/gitian-build.sh#L235) need root permission in order to run docker :  
`./bin/make-base-vm --docker --arch amd64 --suite trusty`

Until the user is not doing specific configuration to run docker with his own user.

Should the setup script run as sudo ?

**Comment by micaelmalta** [comment]
@AbcSxyZ I assume you are using ubuntu/debian, right? 

You need those steps to let your user use docker directly without sudo

```
sudo usermod -aG docker `whoami`
newgrp docker
```

I am actually working on a setup manager: https://github.com/micaelmalta/gitian-builder-dogecoin/blob/master/setup_linux_apt_docker.sh

**Comment by AbcSxyZ** [comment]
Right, Debian. And you ? Your distro does not install docker with root by default ?

Yes, in the docker group it works fine, just need to specify the information [or have a way to do the setup] for each distros to avoid the issue.

Are you sure it is interesting to automate this kind of step ? A well organized list of instruction to copy past could also be used for this purpose, it will avoid multiple similar script (less to maintain) and let the user manage it. Redirect to docker for install, list dependencies by distros with potential configs, it can also do the job. Both could have advantage or disadvantage, but just my two cents.

**Comment by micaelmalta** [comment]
Added the automated prerequisite script + some documentations ;)

**Comment by micaelmalta** [comment]
Can I close this one @AbcSxyZ ?
